Piece
Mars-98/chessApp pull request #1
Opened 2020-05-20 23:51 UTC by Mars-98

created folders for respective files

2020-05-21 00:05 UTC, coughenberg requested changes

2020-05-21 00:05 UTC, coughenberg commented on parentPiece/piece.py
> +        self.rank = pRank
What is rank used for?

2020-05-21 00:05 UTC, coughenberg commented on childPiece/bishop.py
> +    def __init__(self, pMove, pPoints, pColor):
You need to add the 'self' variables to the actual class too. currently self.move and the other variables do not exist and therefore cannot be saved

2020-05-21 00:08 UTC, Mars-98 commented on parentPiece/piece.py
> +        self.rank = pRank
will get back to you on that

2020-05-21 00:08 UTC, coughenberg commented
Story ID from ClickUp?

2020-05-21 00:08 UTC, Mars-98 commented on childPiece/bishop.py
> +    def __init__(self, pMove, pPoints, pColor):
okay, will do

2020-05-21 00:14 UTC, Mars-98 commented on parentPiece/piece.py
> +        self.rank = pRank
I will check in with @PeterX1013

2020-05-21 01:54 UTC, coughenberg commented on childPiece/bishop.py
> +    def __init__(self, pMove, pPoints, pColor):
Also I just realized, why is it called pMove instead of move?
Also, if you are sticking with this name, pMove -> p_move. So it needs to be from pascalCase to snake_case as here https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

2020-05-25 02:35 UTC, Mars-98 commented on childPiece/bishop.py
> +    def __init__(self, pMove, pPoints, pColor):
since the classes we're deleted, we're starting over with the files

2020-05-25 02:36 UTC, Mars-98 commented on parentPiece/piece.py
> +        self.rank = pRank
Discussed with peter today, rank does not need to be on there, more will be explained on design_api doc

2020-05-26 23:26 UTC, coughenberg commented
Can you pull changes from develop into this branch so it is up to date? Also make sure that each commit has an id attached to it. I'll be closing this pull request for now, just reopen a new one when you have changes to merge to develop.

2020-05-26 23:26 UTC, closed without merging