Adding the outline of pieces
Mars-98/chessApp pull request #14
Opened 2020-05-30 22:03 UTC by coughenberg

The basics of each of the piece classes and the overall constructors of them. Soon they will be appearing on the ui. The overall code design of the pieces was done by me, and Connor did the image additions

2020-05-31 02:07 UTC, mattshoobs requested changes
change class name to standards in comment

2020-05-31 02:07 UTC, mattshoobs commented on chess-ui/window.py
>  class chessWindow:
Change class name to Camel case per PEP8 https://www.python.org/dev/peps/pep-0008/#class-names

2020-05-31 02:10 UTC, mattshoobs approved these changes

2020-05-31 02:10 UTC, merged

2026-05-08 03:51 UTC, DjRezalVPsy approved these changes