Parent piece
Mars-98/chessApp pull request #8
Opened 2020-05-28 01:35 UTC by Mars-98

I finished implementing the parent piece class, or so I think

2020-05-28 01:45 UTC, coughenberg requested changes

2020-05-28 01:45 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +    def __del__(self, piece_move_cnt, piece_points, piece_color, piece_crnt_loc):
Nice, I like this innate usage of a method.

2020-05-28 01:45 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +        return
Why is it returning nothing?

2020-05-28 01:45 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +        pass
Do abstract methods just need to exist and have a pass? If so, in Python would it be possible to make an abstract method without colons? It might not work, but it is a possibility because it is done in other languages.

2020-05-28 01:46 UTC, coughenberg commented
Once I look at the comments and receive answers, I will approve or request those changes to occur

2020-05-28 01:47 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +        pass
This is fine, we talked about it.

2020-05-28 01:56 UTC, coughenberg requested changes

2020-05-28 01:56 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +    def capture(self, my_piece, enemy_piece):
Save this so we know how many pieces each player has left somehow

2020-05-28 01:56 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +        return
We talked about this, delete this. Message if needed more explanation.

2020-05-28 02:06 UTC, coughenberg requested changes

2020-05-28 02:06 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +        return
Actually don't delete this. We will may need it for special moves, like castling. Both you and Peter need to discuss who keeps track of what pieces have moved and why. I feel like there should be a rather simple way to deal with it. Either the api or ui will need to keep track of the boolean specifically. But both the api and ui will probably need to use the boolean of whether the piece has moved or not.

2020-05-30 01:04 UTC, coughenberg commented
What is the status on this pull request?

2020-05-30 01:12 UTC, Mars-98 commented
Just started working on the project, do I make another pull request from the same branch or do you close this pull request and I'd make it again?

2020-05-30 01:21 UTC, coughenberg commented
Before I can do anything with this PR, I have to know what the answers are to my questions above. If you have fixes that pertain to this branch then I can keep it open for you. Else I will close it after I get some answers on the making of other files

2020-05-30 01:23 UTC, Mars-98 commented on chess-api/parentPiece/parentPiece.py
> +    def capture(self, my_piece, enemy_piece):
I implemented a global variable and changed it inside of the capture method using the global keyword

2020-05-30 01:24 UTC, Mars-98 commented
Yes, I've finished implementing the changes you wanted, which was just tracking the number of pieces each player has. And everything else I've left alone

2020-05-30 01:25 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +        return
Sorry I didn't realize GitHub resolved this, but this is particularly what I was talking about

2020-05-30 01:26 UTC, coughenberg commented
I made a comment above, I think I accidentally resolved a conversation

2020-05-30 01:30 UTC, Mars-98 commented on chess-api/parentPiece/parentPiece.py
> +        return
No problem, I'm talking to peter about it rn. Will resolve this and lyk when I've finished with this pull request

2020-05-30 04:27 UTC, Mars-98 commented
We resolved the issue and I pushed the new parent class, seems like i cant create another push request on it, so we may need to close this one

2020-05-30 04:43 UTC, coughenberg commented
Yeah, you can only have one PR per branch at a time. What was the resolution of the move method and why? Who is now keeping track of each pieces movement and passing it to the other person?

2020-05-30 04:53 UTC, coughenberg requested changes

2020-05-30 04:53 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +    def capture(self, my_piece, enemy_piece):
Don't implement a global, instead call the variable with self. Globals are considered bad form in Python and programming in general. Although it is still in the language, 99% of the time there is a way to avoid it.

Also, I think you are using my_piece instead of self. Self is what Python uses in place of this in Java. Here is what self is in Python https://www.geeksforgeeks.org/self-in-python-class/

2020-05-30 17:37 UTC, Mars-98 commented
So we've decided to remove the move method. Originally we only needed it for keeping track of the first movement of the pieces. That doesn't really matter for all though, just for pawn, king, and rook. So what we're going to do is remove it, and pass a boolean piece_first_move variable in the constructor. So when the UI calls the move_loc method, and decides to move the piece, Tim would have to change the status of the piece_first_move variable. It will only be changed from F to T on the first move then it's left alone and will no longer need a check. lmk what you think

2020-05-30 17:46 UTC, Mars-98 commented on chess-api/parentPiece/parentPiece.py
> +    def capture(self, my_piece, enemy_piece):
okay, I've changed the code, it makes sense since is is an instance of that class and I'm passing in my_piece which is basically that instance, based on my understanding? lmk what you think. I've implemented all the change on the piece class

2020-05-30 18:02 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +    def capture(self, my_piece, enemy_piece):
Can you push again? Cause I can't see the changes. But yeah from your wording it sounds like what you are saying is correct, where my_piece is essentially just self

2020-05-30 18:04 UTC, coughenberg commented
Yes, that sounds good :)

2020-05-30 18:05 UTC, coughenberg requested changes

2020-05-30 18:05 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +    def capture(my_piece, enemy_piece):
You should be deleting my_piece, not self. Self is what the reference to the instance of the object is

2020-05-30 18:05 UTC, Mars-98 commented
sounds good, I just pushed!

2020-05-30 18:06 UTC, Mars-98 commented on chess-api/parentPiece/parentPiece.py
> +    def capture(my_piece, enemy_piece):
Oh I assumed it'd be easier wording, bc my_piece is still self, despite the different variable name, but okay sounds good

2020-05-30 18:06 UTC, Mars-98 commented on chess-api/parentPiece/parentPiece.py
> +    def capture(my_piece, enemy_piece):
Since it's the first argument passed in, it takes in as self, so either or wouldn't matter

2020-05-30 18:17 UTC, coughenberg commented on chess-api/parentPiece/parentPiece.py
> +    def capture(my_piece, enemy_piece):
Yeah, I agree. But according to PEP8 it should always be named self https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments

2020-05-30 19:21 UTC, Mars-98 commented on chess-api/parentPiece/parentPiece.py
> +    def capture(my_piece, enemy_piece):
okay, sorry I should be looking these things up myself. Just fixed it and pushed

2020-05-30 19:26 UTC, coughenberg approved these changes

2020-05-30 19:26 UTC, merged